# Generated by Django 4.1.6 on 2023-03-11 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0009_appliances"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="landlord",
            field=models.ForeignKey(
                help_text=" this provides the recipients to which this message will be sent to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Landlord_properties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Landlord",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="properties",
            field=models.ForeignKey(
                blank=True,
                help_text="Properties assigned to a tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.properties",
                verbose_name="Properties",
            ),
        ),
    ]
