# Generated by Django 4.1.6 on 2023-03-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_tenant_landlord_alter_tenant_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rented", "Rented"),
                    ("processing", "Processing"),
                    ("declined", "Declined"),
                    ("review", "Review"),
                ],
                help_text="This is the action to take place when applying for this property.",
                max_length=20,
                null=True,
                verbose_name="Action",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="action_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the date when the action was taken.",
                null=True,
                verbose_name="Action Date",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="notification",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="This indicates if the notification option type is enabled True or False.",
                null=True,
                verbose_name="Notification",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="status",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" this indicates if the status option type is enabled True or False.",
                null=True,
                verbose_name="Active",
            ),
        ),
    ]
