# Generated by Django 4.1.6 on 2023-03-15 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "tenants",
            "0003_tenant_action_tenant_action_date_tenant_notification_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="user",
            field=models.ForeignKey(
                help_text=" this provides the sender who is sendin the message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Tenant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tenant",
            ),
        ),
        migrations.CreateModel(
            name="Applicant_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="This is the tenant full name as it appears in their valid ID",
                        max_length=250,
                        null=True,
                        verbose_name="First Name and Last Name",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="This is the tenant date of birth as it is on ID",
                        max_length=100,
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        blank=True,
                        help_text="National Identification Number",
                        max_length=100,
                        null=True,
                        verbose_name="NIN",
                    ),
                ),
                (
                    "bvn",
                    models.CharField(
                        blank=True,
                        help_text="Bank Verification Number",
                        max_length=100,
                        null=True,
                        verbose_name="BVN",
                    ),
                ),
                (
                    "email_address",
                    models.CharField(
                        blank=True,
                        help_text=" Holds extra/alternatve email address of the tenant",
                        max_length=250,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "Phone_number",
                    models.CharField(
                        blank=True,
                        help_text=" Holds tenants extra phone/alternative Number",
                        max_length=100,
                        null=True,
                        verbose_name="Phone Number 2",
                    ),
                ),
                (
                    "drivers_license",
                    models.CharField(
                        blank=True,
                        help_text=" Tenants drivers license",
                        max_length=100,
                        null=True,
                        verbose_name="Driver's License",
                    ),
                ),
                (
                    "family_size",
                    models.CharField(
                        blank=True,
                        help_text="This holds the total number of the fmily or its size",
                        max_length=100,
                        null=True,
                        verbose_name="Family Size",
                    ),
                ),
                (
                    "personal_references",
                    models.CharField(
                        blank=True,
                        help_text=" Personal references, their names and contact info",
                        max_length=100,
                        null=True,
                        verbose_name="Personal References",
                    ),
                ),
                (
                    "rental_history",
                    models.CharField(
                        blank=True,
                        help_text="This holds the tenants rental history, comments, reviews and rental payment history, etc",
                        max_length=100,
                        null=True,
                        verbose_name="Rental History",
                    ),
                ),
                (
                    "employment_income",
                    models.CharField(
                        blank=True,
                        help_text=" this holds the tenant employment income history, tax etc",
                        max_length=100,
                        null=True,
                        verbose_name="Employment Income",
                    ),
                ),
                (
                    "credit_check",
                    models.FileField(
                        blank=True,
                        help_text=" this holds the tenant bank statement",
                        null=True,
                        upload_to="",
                        verbose_name="credit Check",
                    ),
                ),
                (
                    "criminal_security_background_check",
                    models.FileField(
                        blank=True,
                        help_text="holds the tenant files for background follow",
                        null=True,
                        upload_to="",
                        verbose_name="NIN",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text=" this indicates if the status option type is enabled True or False.",
                        null=True,
                        verbose_name="Active",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant application informations.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text=" this provides the sender who is sendin the message",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Tenants_form",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tenant_form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant_Information",
                "verbose_name_plural": "Applicant_Information",
            },
        ),
    ]
