# Generated by Django 4.1.6 on 2023-03-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_alter_tenant_user_applicant_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant_information",
            name="credit_check",
            field=models.FileField(
                blank=True,
                help_text=" This is for uploading the tenant bank statement",
                null=True,
                upload_to="",
                verbose_name="credit Check",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="criminal_security_background_check",
            field=models.FileField(
                blank=True,
                help_text="Tolds the tenant files for background information",
                null=True,
                upload_to="",
                verbose_name="Criminal Security Background Check",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="employment_income",
            field=models.FileField(
                blank=True,
                help_text=" This holds the tenant employment income history, tax etc",
                null=True,
                upload_to="",
                verbose_name="Employment Income",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="status",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" This indicates if the status option type is enabled True or False.",
                null=True,
                verbose_name="Active",
            ),
        ),
    ]
