# Generated by Django 4.1.6 on 2023-03-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_remove_applicant_information_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant_information",
            name="credit_check",
            field=models.ImageField(
                blank=True,
                help_text=" This is for uploading the tenant bank statement",
                null=True,
                upload_to="photos/applicant_image",
                verbose_name="credit Check",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="criminal_security_background_check",
            field=models.ImageField(
                blank=True,
                help_text="Holds the tenant files for background information",
                null=True,
                upload_to="photos/applicant_image",
                verbose_name="Criminal Security Background Check",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="This is the tenant date of birth as it is on ID",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="drivers_license",
            field=models.ImageField(
                blank=True,
                help_text=" Tenants drivers license",
                null=True,
                upload_to="photos/applicant_image",
                verbose_name="Driver's License",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="employment_income",
            field=models.CharField(
                blank=True,
                help_text=" This holds the tenant employment income history, tax etc",
                max_length=100,
                null=True,
                verbose_name="Employment Income",
            ),
        ),
        migrations.AlterField(
            model_name="applicant_information",
            name="nin",
            field=models.ImageField(
                blank=True,
                help_text="National Identification Number",
                null=True,
                upload_to="photos/applicant_image",
                verbose_name="NIN",
            ),
        ),
    ]
