# Generated by Django 4.1.6 on 2023-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_alter_applicant_information_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant_information",
            name="date_of_birth",
            field=models.CharField(
                blank=True,
                help_text="This is the tenant date of birth as it is on ID",
                max_length=100,
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
    ]
