# Generated by Django 4.1.6 on 2023-03-17 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0012_remove_applicant_information_tenant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant_information",
            name="landlord",
        ),
    ]
