# Generated by Django 4.1.6 on 2023-03-18 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0013_remove_applicant_information_landlord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Applicant_Information",
        ),
    ]
