# Generated by Django 4.1.6 on 2023-04-29 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0015_tenant_family_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="landlord",
        ),
    ]
