# Generated by Django 4.1.6 on 2023-02-22 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Esate_Messages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        blank=True,
                        help_text="this fields requires the message type of which the message will be sent with and categorized into",
                        max_length=255,
                        null=True,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text=" The subject line of an email is the single line of text people see when they receive your email. This one line of text can often determine whether an email is opened or sent straight to the trash, so make sure it's optimized for your audience ",
                        max_length=255,
                        null=True,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text=" The body is the actual text of the email. Generally, you'll write this just like a normal letter, with a greeting, one or more paragraphs, and a closing with your name. ",
                        null=True,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text=" this indicates is the active messages is enabled or not ",
                        null=True,
                        verbose_name="Active",
                    ),
                ),
                (
                    "recipients",
                    models.ForeignKey(
                        help_text=" this provides the recipients to which this message will be sent to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_recipients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Message Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messages",
                "verbose_name_plural": "Messages",
                "ordering": ("-created_date",),
            },
        ),
    ]
