# Generated by Django 4.1.6 on 2023-03-08 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inmessages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Esate_Messages",
            new_name="Estate_Messages",
        ),
    ]
