# Generated by Django 4.1.6 on 2023-03-20 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inmessages", "0005_rename_body_estate_messages_message_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estate_messages",
            old_name="subject",
            new_name="subject_heading",
        ),
    ]
