# Generated by Django 4.1.6 on 2023-02-21 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_alter_properties_other_amenities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Properties  image for the current properties, which should be in PNG, JPEG, or JPG format",
                        null=True,
                        upload_to="photos/properties_image",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="Product of which the images belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.properties",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
                "ordering": ("-created_date",),
            },
        ),
    ]
