# Generated by Django 4.1.6 on 2023-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="this is the rent fee that will be paid by the tenant",
                max_digits=300,
                null=True,
                verbose_name="Amount ",
            ),
        ),
    ]
