# Generated by Django 4.1.6 on 2023-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_properties_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property_type",
            name="active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" this indicates if the active property type is enabled or not ",
                null=True,
                verbose_name="Active",
            ),
        ),
    ]
