# Generated by Django 4.1.6 on 2023-02-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_alter_property_type_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="other_amenities",
            name="amenity",
        ),
        migrations.RemoveField(
            model_name="outdoor_spaces",
            name="outdoor_space",
        ),
        migrations.RemoveField(
            model_name="parking_type",
            name="parking_type",
        ),
        migrations.RemoveField(
            model_name="property_type",
            name="property_type",
        ),
        migrations.RemoveField(
            model_name="utilities",
            name="utility",
        ),
        migrations.AddField(
            model_name="other_amenities",
            name="option",
            field=models.CharField(
                blank=True,
                help_text="Option type refers to property options that will be used during uploading of properties by the property owner or landlord ",
                max_length=255,
                null=True,
                verbose_name="Option Type",
            ),
        ),
        migrations.AddField(
            model_name="outdoor_spaces",
            name="option",
            field=models.CharField(
                blank=True,
                help_text="Option type refers to property options that will be used during uploading of properties by the property owner or landlord ",
                max_length=255,
                null=True,
                verbose_name="Option Type",
            ),
        ),
        migrations.AddField(
            model_name="parking_type",
            name="option",
            field=models.CharField(
                blank=True,
                help_text="Option type refers to property options that will be used during uploading of properties by the property owner or landlord ",
                max_length=255,
                null=True,
                verbose_name="Option Type",
            ),
        ),
        migrations.AddField(
            model_name="property_type",
            name="option",
            field=models.CharField(
                blank=True,
                help_text="Option type refers to property options that will be used during uploading of properties by the property owner or landlord ",
                max_length=255,
                null=True,
                verbose_name="Option Type",
            ),
        ),
        migrations.AddField(
            model_name="utilities",
            name="option",
            field=models.CharField(
                blank=True,
                help_text="Option type refers to property options that will be used during uploading of properties by the property owner or landlord ",
                max_length=255,
                null=True,
                verbose_name="Option Type",
            ),
        ),
        migrations.AlterField(
            model_name="other_amenities",
            name="active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" this indicates if the active option type is enabled or not ",
                null=True,
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="outdoor_spaces",
            name="active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" this indicates if the active option type is enabled or not ",
                null=True,
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="parking_type",
            name="active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" this indicates if the active option type is enabled or not ",
                null=True,
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="property_type",
            name="active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" this indicates if the active option type is enabled or not ",
                null=True,
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="utilities",
            name="active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=" this indicates if the active option type is enabled or not ",
                null=True,
                verbose_name="Active",
            ),
        ),
    ]
