# Generated by Django 4.1.6 on 2023-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_remove_other_amenities_amenity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="other_amenities",
            options={
                "verbose_name": "Other Amenities Space",
                "verbose_name_plural": "Other Amenities Space",
            },
        ),
        migrations.AddField(
            model_name="properties",
            name="ac_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("window", "Cooling"),
                    ("split", "Split"),
                    ("central", "Central"),
                    ("none", "None"),
                ],
                help_text=" This is the ac type of the property",
                max_length=20,
                null=True,
                verbose_name="AC Type",
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="floor_area",
            field=models.CharField(
                blank=True,
                choices=[("sq_feet", "sq_feet"), ("sq_m", "sq_m")],
                help_text=" This is the floor area of the property",
                max_length=20,
                null=True,
                verbose_name="Floor Area",
            ),
        ),
    ]
