# Generated by Django 4.1.6 on 2023-02-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0007_alter_other_amenities_options_properties_ac_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="properties_image",
            field=models.ImageField(
                blank=True,
                help_text="Properties  image for the current properties, which should be in PNG, JPEG, or JPG format",
                null=True,
                upload_to="photos/properties_image",
                verbose_name="Property Image",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="properties_video",
            field=models.FileField(
                blank=True,
                help_text="Properties  video for the current properties, which should be in mp4 format",
                null=True,
                upload_to="videos/properties_videos",
                verbose_name="Property Video",
            ),
        ),
    ]
