# Generated by Django 4.1.6 on 2023-02-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_alter_properties_properties_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appliances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        blank=True,
                        help_text="Option type refers to property options that will be used during uploading of properties by the property owner or landlord ",
                        max_length=255,
                        null=True,
                        verbose_name="Option Type",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text=" this indicates if the active option type is enabled or not ",
                        null=True,
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "appliances",
                "verbose_name_plural": "appliances",
            },
        ),
    ]
