# Generated by Django 4.1.6 on 2023-03-16 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0009_appliances"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="This comment is made for the property",
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="This property has been commented on.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.properties",
                        verbose_name="Property Comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="This profile belongs to the commenter",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserComments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Commenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "All Property Comments",
                "verbose_name_plural": "All Properties Comments",
            },
        ),
    ]
