# Generated by Django 4.1.6 on 2023-03-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="number_of_bedroom_and_bathroon",
            field=models.CharField(
                blank=True,
                help_text=" Number of Rooms or Bathrooms means total number of rooms or bathrooms within a  property. ",
                max_length=100,
                null=True,
                verbose_name="Number of Bedrooms and Bathrooms",
            ),
        ),
        migrations.AlterField(
            model_name="properties",
            name="number_of_storeys",
            field=models.CharField(
                blank=True,
                help_text=" Number of levels of living area a dwelling has above grade. Examples: A ranch is typically a 1- story dwelling or 1 story with attic. A cape is typically a 1.5 or 1.75 story home. Colonials are typically denoted with a 2 story, 2 story with attic, and 2.5 dwellings. ",
                max_length=100,
                null=True,
                verbose_name="Number of Storeys",
            ),
        ),
    ]
