# Generated by Django 4.1.6 on 2023-04-05 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_comments_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
