# Generated by Django 4.1.6 on 2023-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0013_delete_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="appliances",
            field=models.ManyToManyField(
                help_text=' Appliances are device or piece of equipment designed to perform a specific task. electrical and gas appliances" ',
                to="properties.appliances",
                verbose_name="Appliances",
            ),
        ),
    ]
