# Generated by Django 4.1.6 on 2023-03-29 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_pin",
                    models.CharField(
                        help_text=" otp of the user ",
                        max_length=6,
                        null=True,
                        verbose_name="OTP",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the user",
                        max_length=254,
                        null=True,
                        verbose_name=" OTP ",
                    ),
                ),
                (
                    "pin_duration",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="this holds the duration of pin sent to the user",
                        null=True,
                        verbose_name="OTP Pin duration",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="this is the users otp status if active of not",
                        null=True,
                        verbose_name="Active",
                    ),
                ),
            ],
        ),
    ]
