# Generated by Django 4.1.6 on 2023-04-11 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenance",
            options={
                "ordering": ("-created_date",),
                "verbose_name": "Maintenance",
                "verbose_name_plural": "Maintenance",
            },
        ),
    ]
