# Generated by Django 4.1.6 on 2023-03-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                        help_text="gender of the user",
                        max_length=50,
                        null=True,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="date of birth of applicant",
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_profile_image",
                        verbose_name="Holds the users profile yesterday",
                    ),
                ),
                (
                    "nin",
                    models.ImageField(
                        blank=True,
                        help_text="National Identification Number",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="NIN",
                    ),
                ),
                (
                    "bvn",
                    models.CharField(
                        blank=True,
                        help_text="Bank Verification Number",
                        max_length=100,
                        null=True,
                        verbose_name="BVN",
                    ),
                ),
                (
                    "drivers_license",
                    models.ImageField(
                        blank=True,
                        help_text=" Tenants drivers license",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="Driver's License",
                    ),
                ),
                (
                    "family_size",
                    models.CharField(
                        blank=True,
                        help_text="This holds the total number of the fmily or its size",
                        max_length=100,
                        null=True,
                        verbose_name="Family Size",
                    ),
                ),
                (
                    "personal_references",
                    models.CharField(
                        blank=True,
                        help_text=" Personal references, their names and contact info",
                        max_length=100,
                        null=True,
                        verbose_name="Personal References",
                    ),
                ),
                (
                    "rental_history",
                    models.CharField(
                        blank=True,
                        help_text="This holds the tenants rental history, comments, reviews and rental payment history, etc",
                        max_length=250,
                        null=True,
                        verbose_name="Rental History",
                    ),
                ),
                (
                    "employment_income",
                    models.CharField(
                        blank=True,
                        help_text=" This holds the tenant employment income history, tax etc",
                        max_length=100,
                        null=True,
                        verbose_name="Employment Income",
                    ),
                ),
                (
                    "credit_check",
                    models.ImageField(
                        blank=True,
                        help_text=" This is for uploading the tenant bank statement",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="credit Check",
                    ),
                ),
                (
                    "criminal_security_background_check",
                    models.ImageField(
                        blank=True,
                        help_text="Holds the tenant files for background information",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="Criminal Security Background Check",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text=" This indicates if the status option type is enabled True or False.",
                        null=True,
                        verbose_name="Active",
                    ),
                ),
            ],
        ),
    ]
