# Generated by Django 4.1.6 on 2023-03-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_applicant_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant_information",
            name="user_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
