# Generated by Django 4.1.6 on 2023-03-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(
                help_text="contact number of the customer.",
                max_length=100,
                null=True,
                verbose_name="Contact Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="The first names of the customer.",
                max_length=100,
                null=True,
                verbose_name="First names",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="The last names of the customer.",
                max_length=100,
                null=True,
                verbose_name="Last names",
            ),
        ),
    ]
