# Generated by Django 4.1.6 on 2023-03-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_applicant_information_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant_information",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Address of the user.",
                max_length=300,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="applicant_information",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name of the user.",
                max_length=200,
                null=True,
                verbose_name="First Name",
            ),
        ),
        migrations.AddField(
            model_name="applicant_information",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Surname or family name of the user.",
                max_length=200,
                null=True,
                verbose_name="Last Name",
            ),
        ),
    ]
