# Generated by Django 4.1.6 on 2023-03-24 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_applicant_information_address_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Applicant_Information",
        ),
    ]
