# Generated by Django 4.1.6 on 2023-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_applicant_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(
                blank=True,
                help_text="The secret key for generating OTPs.",
                max_length=16,
                null=True,
                verbose_name="OTP Secret",
            ),
        ),
    ]
