# Generated by Django 4.0.10 on 2023-04-17 10:16

from django.db import migrations, models
import recuity.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'users  Account', 'verbose_name_plural': 'users  Account'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', recuity.users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant')], help_text='Account type is used to identify the account user either the landlord or the tenant.', max_length=50, null=True, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(help_text='contact number of the customer.', max_length=100, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='The first names of the customer.', max_length=100, null=True, verbose_name='First names'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, help_text='this holds the home address of the user.', max_length=250, null=True, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='The last names of the customer.', max_length=100, null=True, verbose_name='Last names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address of the customer.', max_length=150, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
