# Generated by Django 4.1.6 on 2023-03-24 19:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kyc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name of the user.",
                        max_length=200,
                        null=True,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Surname or family name of the user.",
                        max_length=200,
                        null=True,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the user.",
                        max_length=300,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                        help_text="gender of the user",
                        max_length=50,
                        null=True,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="date of birth of applicant",
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_profile_image",
                        verbose_name="Holds the users profile yesterday",
                    ),
                ),
                (
                    "nin",
                    models.ImageField(
                        blank=True,
                        help_text="National Identification Number",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="NIN",
                    ),
                ),
                (
                    "bvn",
                    models.CharField(
                        blank=True,
                        help_text="Bank Verification Number",
                        max_length=100,
                        null=True,
                        verbose_name="BVN",
                    ),
                ),
                (
                    "drivers_license",
                    models.ImageField(
                        blank=True,
                        help_text=" Tenants drivers license",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="Driver's License",
                    ),
                ),
                (
                    "family_size",
                    models.CharField(
                        blank=True,
                        help_text="This holds the total number of the fmily or its size",
                        max_length=100,
                        null=True,
                        verbose_name="Family Size",
                    ),
                ),
                (
                    "personal_references",
                    models.CharField(
                        blank=True,
                        help_text=" Personal references, their names and contact info",
                        max_length=100,
                        null=True,
                        verbose_name="Personal References",
                    ),
                ),
                (
                    "rental_history",
                    models.CharField(
                        blank=True,
                        help_text="This holds the tenants rental history, comments, reviews and rental payment history, etc",
                        max_length=250,
                        null=True,
                        verbose_name="Rental History",
                    ),
                ),
                (
                    "employment_income",
                    models.CharField(
                        blank=True,
                        help_text=" This holds the tenant employment income history, tax etc",
                        max_length=100,
                        null=True,
                        verbose_name="Employment Income",
                    ),
                ),
                (
                    "credit_check",
                    models.ImageField(
                        blank=True,
                        help_text=" This is for uploading the tenant bank statement",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="credit Check",
                    ),
                ),
                (
                    "criminal_security_background_check",
                    models.ImageField(
                        blank=True,
                        help_text="Holds the tenant files for background information",
                        null=True,
                        upload_to="photos/applicant_image",
                        verbose_name="Criminal Security Background Check",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text=" This indicates if the status option type is enabled True or False.",
                        null=True,
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
    ]
