# Generated by Django 4.1.6 on 2023-04-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=250,
                null=True,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="country",
            field=models.ForeignKey(
                help_text="Country where the user stays.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.country",
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="phone_number_1",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=100,
                null=True,
                verbose_name="Phone number 1",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="phone_number_2",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=100,
                null=True,
                verbose_name="Phone number 2",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Holds the users profile image, probably a headshot photo.",
                null=True,
                upload_to="photo/kyc/",
                verbose_name="Profile Image",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="state",
            field=models.ForeignKey(
                help_text="State or province the user stays.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="type_of_identification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRIVERS_LISCENSE", "DRIVERS_LISCENSE"),
                    ("NATIONAL_IDENTIFICATION", "NATIONAL_IDENTIFICATION"),
                    ("INTERNATIONAL_PASSPORT", "INTERNATIONAL_PASSPORT"),
                ],
                help_text="This holds the type of identification ID used",
                max_length=50,
                null=True,
                verbose_name="Type of ID",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="zip_code",
            field=models.CharField(
                blank=True,
                help_text="Zip or Postal code of the users address.",
                max_length=100,
                null=True,
                verbose_name="ZIP/Postal code",
            ),
        ),
    ]
