# Generated by Django 4.1.6 on 2023-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0002_alter_kyc_options_rename_address_kyc_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="phone_number_1",
            field=models.IntegerField(
                blank=True,
                help_text="The city which the user resides.",
                null=True,
                verbose_name="Phone number of the user including country code.",
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="phone_number_2",
            field=models.IntegerField(
                blank=True,
                help_text="The city which the user resides.",
                null=True,
                verbose_name="Phone number of the user including country code.",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="address_line_1",
            field=models.CharField(
                blank=True,
                help_text="Address of the user.",
                max_length=300,
                null=True,
                verbose_name="Address Line 1",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="Address of the user.",
                max_length=300,
                null=True,
                verbose_name="Address Line 2",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=250,
                null=True,
                verbose_name="City or Town where the user stays.",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                help_text="This holds the gender of the user",
                max_length=50,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State or province the user stays.",
                max_length=250,
                null=True,
                verbose_name="State or Province where the user stays.",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="zip_code",
            field=models.CharField(
                blank=True,
                help_text="Zip or Postal code of the users address.",
                max_length=100,
                null=True,
                verbose_name="ZIP Code or Postal code of the user.",
            ),
        ),
    ]
