# Generated by Django 4.1.6 on 2023-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0003_kyc_phone_number_1_kyc_phone_number_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="phone_number_1",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=100,
                null=True,
                verbose_name="Phone number of the user including country code.",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="phone_number_2",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=100,
                null=True,
                verbose_name="Phone number of the user including country code.",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="proof_of_address_type",
            field=models.CharField(
                choices=[
                    ("ELECTRICITY_BILL", "ELECTRICITY BILL"),
                    ("GAS_BILL", "GAS BILL"),
                    ("WATER_BILL", "WATER BILL"),
                    ("SEWER_BILL", "SEWER  BILL"),
                    ("RECYCLING_BILL", "RECYCLING BILL"),
                    ("TV_CABLE_BILL", "TV / CABLE BILL"),
                ],
                help_text=" Holds the type of utility bill the user used for verifications.",
                max_length=250,
                null=True,
                verbose_name=" Prove of address type.",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="second_nationality",
            field=models.CharField(
                blank=True,
                help_text="This holds the users second country of origin if the user has dual citizenship",
                max_length=250,
                null=True,
                verbose_name=" Second Nationality",
            ),
        ),
    ]
