# Generated by Django 4.1.6 on 2023-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0004_alter_kyc_phone_number_1_alter_kyc_phone_number_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="phone_number_1",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=100,
                null=True,
                verbose_name="Phone number 1 of the user including country code.",
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="phone_number_2",
            field=models.CharField(
                blank=True,
                help_text="The city which the user resides.",
                max_length=100,
                null=True,
                verbose_name="Phone number 2 of the user including country code.",
            ),
        ),
    ]
