# Generated by Django 4.1.6 on 2023-04-02 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kyc", "0005_alter_kyc_phone_number_1_alter_kyc_phone_number_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="user_detail",
            field=models.OneToOneField(
                help_text=" this provides the sender who is sending the message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_detail",
            ),
        ),
    ]
