# Generated by Django 4.1.6 on 2023-04-03 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kyc", "0006_alter_kyc_user_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="user_detail",
            field=models.ForeignKey(
                help_text=" this provides the sender who is sending the message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_detail",
            ),
        ),
    ]
